config/routes.rb
Rails.application.routes.draw do
  get "log" => 'sessions#index'
  get "logout" => 'sessions#destroy'
  get "sign" => "users#new"

  resources :posts
  resources :users
  resources :sessions
  resources :hearts, only: :create

  get 'about' => "pages#about"
  root 'pages#welcome'

end

app/models/heart.rb
class Heart < ActiveRecord::Base
	belongs_to :post
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :hearts
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
	def create
		@heart = Heart.new(heart_params)

		if @heart.save
			redirect_to @heart.post, notice: "hearted that post!"
		else
			redirect_to root_url, notice: "error creating heart"
		end
	end
	private
		def heart_params
	    	params.require(:heart).permit(:post_id)
	    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
      redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => user.email
      logged = true
  	else
  		flash.now.alert = "Invalid email and/or password"
  		render "new"
      logged = false
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render action: "new"
  	end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Crumblr</title>
	  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

	  <%= csrf_meta_tags %>
	</head>
	<body>
    <div class="container">
      <div class="page-header">
      <ul class="nav nav-pills pull-right">
        <li>
          <%= link_to "Home", root_url %>
        </li>
       
        <li>
          <%= link_to "Manage Posts", posts_url %>
        </li>

        <li>
          <%= link_to "About", about_url %>
        </li>
        <li>
        <% if current_user %>
          <%= current_user.email %>
          <%= link_to "Log out", logout_url %>
        <% else %>
          <%= link_to "Sign up", sign_url %>
          <%= link_to "Log In", log_url %>
        <% end %>
       </li>
        <li>
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
        </li>
      </ul>
      <h1> 
        <%= link_to 'crumblr', '/'%>
        <small>
          // home baked goodness
        </small>
      </h1>
    </div>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %> 
    </div>
    </div>
    </div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	Welcome to amir's mock site using ruby on rails!
</p>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>

	<br><br>----------------------------------------------<br><br>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :kind %><br>
    <%= f.select :kind, ["text", "image"], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content , class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
	<h2>
	  	<div class="pull-right">
  			<%= form_for(Heart.new) do |f| %>
  				<%= f.hidden_field :post_id, value: post.id %>
  				<%= f.submit "♥", class: 'btn btn-danger' %>
  			<% end %>
  		</div>
  		<%= link_to post.title, post %>
    </h2>
</p>

<p>
	<% if post.kind == "image" %>
		<%= image_tag post.content, style: "width:100%" %>
	<% else %>
		<%= simple_format post.content %>
	<% end %>
</p>

<p class="text-muted">
	<small>
		Post created at: <%= post.created_at.to_formatted_s(:long) %>
	</small>

	<small class="pull-right">
		<%= post.hearts.count %> hearts
	</small>
</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
	<p class='alert alert-success'><%= notice %></p>
<% end %>

<%= render 'post', post: @post %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p class='form group'>
		<%= f.label :email %><br>
		<%= f.text_field :email, class: 'form-control'%>
	</p>
	<p class='form group'>
		<%= f.label :password %></br>
		<%= f.password_field :password, class: 'form-control' %>
	</p>
	<p class='form group'>
		<%= f.label :password_confirmation %></br>
		<%= f.password_field :password_confirmation, class: 'form-control' %>
	</p>
	<p class="actions"> 
		<%= f.submit "Submit", class: 'btn btn-primary' %>
	</p>
<% end %>